"""
Matplotlib visualization utilities for NEPath test suite.

This module provides helper functions for visualizing toolpaths,
contours, holes, sharp corners, and other geometric features
generated by the NEPath library.
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # Use non-interactive backend for tests
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.figure import Figure

from NEPath import Path as NEPath


def plot_paths(
    paths: list[NEPath] | None,
    title: str = "NEPath Toolpaths",
    contour: NEPath | None = None,
    holes: list[NEPath] | None = None,
    sharp_corners: list[tuple[float, float]] | None = None,
    underfill_regions: list[NEPath] | None = None,
    figsize: tuple[float, float] = (10, 10),
) -> tuple[Figure, Axes]:
    """
    Plot toolpaths with optional contour, holes, sharp corners, and underfill regions.

    Parameters
    ----------
    paths : list[NEPath] | None
        List of Path objects to plot
    title : str
        Plot title
    contour : NEPath | None
        Contour boundary to plot
    holes : list[NEPath] | None
        Hole boundaries to plot
    sharp_corners : list[tuple[float, float]] | None
        List of (x, y) sharp corner points to highlight
    underfill_regions : list[NEPath] | None
        Underfill region paths to highlight
    figsize : tuple[float, float]
        Figure size (width, height)

    Returns
    -------
    tuple[Figure, Axes]
        Matplotlib figure and axis objects
    """
    fig, ax = plt.subplots(figsize=figsize)

    # Generate colors for paths using a colormap
    cmap = plt.cm.viridis
    n_paths = len(paths) if paths else 1

    # Plot contour if provided
    if contour is not None:
        x, y = contour.get_arrays()
        ax.plot(x, y, "k-", linewidth=2, label="Contour", zorder=10)

    # Plot holes if provided
    if holes:
        for i, hole in enumerate(holes):
            x, y = hole.get_arrays()
            ax.plot(x, y, "k--", linewidth=2, label="Hole" if i == 0 else None, zorder=10)

    # Plot underfill regions if provided
    if underfill_regions:
        for i, region in enumerate(underfill_regions):
            x, y = region.get_arrays()
            ax.fill(x, y, alpha=0.3, color="red", label="Underfill" if i == 0 else None, zorder=1)

    # Plot toolpaths
    if paths:
        for i, path in enumerate(paths):
            x, y = path.get_arrays()
            color = cmap(i / n_paths)
            ax.plot(x, y, "-", color=color, linewidth=1, alpha=0.8, zorder=5)
            # Mark start and end points
            if len(x) > 0:
                ax.plot(x[0], y[0], "go", markersize=4, zorder=15)  # Start: green
                ax.plot(x[-1], y[-1], "ro", markersize=4, zorder=15)  # End: red

    # Plot sharp corners if provided
    if sharp_corners:
        sc_x, sc_y = zip(*sharp_corners) if sharp_corners else ([], [])
        ax.scatter(sc_x, sc_y, c="orange", s=100, marker="*", label="Sharp corners", zorder=20, edgecolors="black")

    ax.set_aspect("equal")
    ax.set_title(title)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.grid(True, alpha=0.3)

    # Add legend if we have labeled items
    handles, labels = ax.get_legend_handles_labels()
    if handles:
        ax.legend(loc="upper right")

    # Add path count annotation
    if paths:
        ax.annotate(
            f"{len(paths)} paths", xy=(0.02, 0.98), xycoords="axes fraction", fontsize=10, verticalalignment="top", bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5)
        )

    plt.tight_layout()
    return fig, ax


def save_plot(fig: Figure, output_dir: str | Path, filename: str) -> Path:
    """
    Save a figure to the output directory.

    Parameters
    ----------
    fig : Figure
        The matplotlib figure to save
    output_dir : str | Path
        Directory to save the figure to
    filename : str
        Name of the output file (e.g., 'demo_CP.png')

    Returns
    -------
    Path
        Path to the saved file
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    filepath = output_path / filename
    fig.savefig(filepath, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return filepath


def plot_comparison(
    original_path: NEPath,
    resampled_path: NEPath,
    title: str = "Path Comparison",
    figsize: tuple[float, float] = (14, 5),
) -> tuple[Figure, list[Axes]]:
    """
    Plot original and resampled paths side by side for comparison.

    Parameters
    ----------
    original_path : NEPath
        The original path object
    resampled_path : NEPath
        The resampled path object
    title : str
        Overall title for the comparison
    figsize : tuple[float, float]
        Figure size (width, height)

    Returns
    -------
    tuple[Figure, list[Axes]]
        Matplotlib figure and list of axes objects
    """
    fig, axes = plt.subplots(1, 2, figsize=figsize)

    # Original path
    x_orig, y_orig = original_path.get_arrays()
    axes[0].plot(x_orig, y_orig, "b-o", markersize=8, label=f"Original ({original_path.length} pts)")
    axes[0].set_title("Original Path")
    axes[0].set_xlabel("X")
    axes[0].set_ylabel("Y")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    axes[0].set_aspect("equal")

    # Resampled path
    x_res, y_res = resampled_path.get_arrays()
    axes[1].plot(x_res, y_res, "r-o", markersize=4, label=f"Resampled ({resampled_path.length} pts)")
    axes[1].set_title("Resampled Path")
    axes[1].set_xlabel("X")
    axes[1].set_ylabel("Y")
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)
    axes[1].set_aspect("equal")

    fig.suptitle(title)
    plt.tight_layout()
    return fig, list(axes)
