"""
Matplotlib visualization utilities for NEPath test suite.

This module provides helper functions for visualizing toolpaths,
contours, holes, sharp corners, and other geometric features
generated by the NEPath library.
"""

from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # Use non-interactive backend for tests
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
from matplotlib.figure import Figure

from NEPath import Path as NEPath

IQOP_OVERLAY_FIGURE_SIZE = (15.0, 7.0)
IQOP_REGISTRATION_MIN_SAMPLES = 64
IQOP_ARC_LENGTH_ULP_MULTIPLIER = 64.0
IQOP_GUROBI_COLOR = "#d97706"
IQOP_IPOPT_COLOR = "#2563eb"
IQOP_DELTA_COLOR = "#7c3aed"
IQOP_GRID_ALPHA = 0.25
IQOP_GUROBI_LINE_WIDTH = 3.2
IQOP_IPOPT_LINE_WIDTH = 1.2
IQOP_GUROBI_ALPHA = 0.85
IQOP_DELTA_ALPHA = 0.72
IQOP_DELTA_LINE_WIDTH = 1.5
IQOP_SCIENTIFIC_NOTATION_LIMITS = (-2, 2)


class IqopOverlayError(RuntimeError):
    """Base error for an invalid IQOP solver comparison."""


class IqopPathCountMismatchError(IqopOverlayError):
    """Raised when solver outputs contain different path counts."""


class IqopDegeneratePathError(IqopOverlayError):
    """Raised when a solver path has no measurable arc length."""


class IqopNonFinitePathError(IqopOverlayError):
    """Raised when a solver path contains NaN or infinite coordinates."""


@dataclass(frozen=True)
class IqopSolverOverlayMetrics:
    """Registered geometric separation between Gurobi and Ipopt paths."""

    path_max: tuple[float, ...]
    path_rms: tuple[float, ...]
    global_max: float
    global_rms: float


def _path_coordinates(path: NEPath) -> tuple[np.ndarray, np.ndarray]:
    x_raw, y_raw = path.get_arrays()
    x = np.asarray(x_raw, dtype=np.float64)
    y = np.asarray(y_raw, dtype=np.float64)
    if x.ndim != 1 or y.ndim != 1 or x.size != y.size or x.size < 2:
        raise IqopDegeneratePathError("IQOP overlay paths require matching one-dimensional x/y arrays")
    if not np.all(np.isfinite(x)) or not np.all(np.isfinite(y)):
        raise IqopNonFinitePathError("IQOP overlay paths must contain finite coordinates")
    return x, y


def _resample_by_arclength(
    path: NEPath,
    sample_count: int,
) -> tuple[np.ndarray, np.ndarray, bool]:
    x, y = _path_coordinates(path)
    scale = max(float(np.ptp(x)), float(np.ptp(y)), 1.0)
    arc_floor = IQOP_ARC_LENGTH_ULP_MULTIPLIER * np.finfo(np.float64).eps * scale
    segment_lengths = np.hypot(np.diff(x), np.diff(y))
    keep = np.concatenate((np.array([True]), segment_lengths > arc_floor))
    x = x[keep]
    y = y[keep]
    if x.size < 2:
        raise IqopDegeneratePathError("IQOP overlay paths must have non-zero arc length")

    cumulative = np.concatenate((np.array([0.0]), np.cumsum(np.hypot(np.diff(x), np.diff(y)))))
    total_length = float(cumulative[-1])
    if total_length <= arc_floor:
        raise IqopDegeneratePathError("IQOP overlay paths must have non-zero arc length")

    closure_distance = float(np.hypot(x[-1] - x[0], y[-1] - y[0]))
    is_closed = closure_distance <= arc_floor
    targets = np.linspace(0.0, total_length, sample_count, endpoint=not is_closed)
    return np.interp(targets, cumulative, x), np.interp(targets, cumulative, y), is_closed


def _registered_separations(ipopt_path: NEPath, gurobi_path: NEPath) -> np.ndarray:
    ipopt_x_raw, _ = _path_coordinates(ipopt_path)
    gurobi_x_raw, _ = _path_coordinates(gurobi_path)
    sample_count = max(IQOP_REGISTRATION_MIN_SAMPLES, ipopt_x_raw.size, gurobi_x_raw.size)
    ipopt_x, ipopt_y, ipopt_closed = _resample_by_arclength(ipopt_path, sample_count)
    gurobi_x, gurobi_y, gurobi_closed = _resample_by_arclength(gurobi_path, sample_count)
    if ipopt_closed != gurobi_closed:
        raise IqopOverlayError("Corresponding IQOP paths disagree on open/closed topology")

    orientations = ((gurobi_x, gurobi_y), (gurobi_x[::-1], gurobi_y[::-1]))
    best_error = np.inf
    aligned_x: np.ndarray | None = None
    aligned_y: np.ndarray | None = None
    shifts = range(sample_count) if ipopt_closed else (0,)
    for oriented_x, oriented_y in orientations:
        for shift in shifts:
            candidate_x = np.roll(oriented_x, shift) if ipopt_closed else oriented_x
            candidate_y = np.roll(oriented_y, shift) if ipopt_closed else oriented_y
            mean_squared_error = float(np.mean(np.square(ipopt_x - candidate_x) + np.square(ipopt_y - candidate_y)))
            if mean_squared_error < best_error:
                best_error = mean_squared_error
                aligned_x = candidate_x
                aligned_y = candidate_y
    if aligned_x is None or aligned_y is None:
        raise IqopOverlayError("IQOP path registration produced no alignment candidate")
    return np.hypot(ipopt_x - aligned_x, ipopt_y - aligned_y)


def plot_iqop_solver_overlay(
    ipopt_paths: list[NEPath],
    gurobi_paths: list[NEPath],
    title: str = "IQOP Gurobi vs ifopt / Ipopt",
) -> tuple[Figure, list[Axes], IqopSolverOverlayMetrics]:
    """Plot solver paths in one coordinate frame and quantify registered deltas.

    Args:
        ipopt_paths: IQOP output from the ifopt/Ipopt implementation.
        gurobi_paths: IQOP output from the Gurobi implementation.
        title: Overall figure title.

    Returns:
        Figure, overlay/delta axes, and registered separation metrics.

    Raises:
        IqopPathCountMismatchError: If solvers return different path counts.
        IqopDegeneratePathError: If a path cannot be registered by arc length.
        IqopNonFinitePathError: If a path contains non-finite coordinates.
    """
    if not ipopt_paths or not gurobi_paths or len(ipopt_paths) != len(gurobi_paths):
        raise IqopPathCountMismatchError(f"IQOP overlay requires equal non-zero path counts; got Ipopt={len(ipopt_paths)}, Gurobi={len(gurobi_paths)}")

    separations = tuple(_registered_separations(ipopt_path, gurobi_path) for ipopt_path, gurobi_path in zip(ipopt_paths, gurobi_paths, strict=True))
    path_max = tuple(float(np.max(delta)) for delta in separations)
    path_rms = tuple(float(np.sqrt(np.mean(np.square(delta)))) for delta in separations)
    all_deltas = np.concatenate(separations)
    metrics = IqopSolverOverlayMetrics(
        path_max=path_max,
        path_rms=path_rms,
        global_max=float(np.max(all_deltas)),
        global_rms=float(np.sqrt(np.mean(np.square(all_deltas)))),
    )

    figure, axes_array = plt.subplots(1, 2, figsize=IQOP_OVERLAY_FIGURE_SIZE)
    overlay_axes, delta_axes = axes_array
    for index, (ipopt_path, gurobi_path) in enumerate(zip(ipopt_paths, gurobi_paths, strict=True)):
        gurobi_x, gurobi_y = _path_coordinates(gurobi_path)
        ipopt_x, ipopt_y = _path_coordinates(ipopt_path)
        gurobi_label = "Gurobi" if index == 0 else None
        ipopt_label = "ifopt / Ipopt" if index == 0 else None
        overlay_axes.plot(
            gurobi_x,
            gurobi_y,
            color=IQOP_GUROBI_COLOR,
            linestyle="--",
            linewidth=IQOP_GUROBI_LINE_WIDTH,
            alpha=IQOP_GUROBI_ALPHA,
            label=gurobi_label,
        )
        overlay_axes.plot(
            ipopt_x,
            ipopt_y,
            color=IQOP_IPOPT_COLOR,
            linewidth=IQOP_IPOPT_LINE_WIDTH,
            label=ipopt_label,
        )

    overlay_axes.set_aspect("equal", adjustable="datalim")
    overlay_axes.set_title("Registered toolpath overlay")
    overlay_axes.set_xlabel("X")
    overlay_axes.set_ylabel("Y")
    overlay_axes.grid(alpha=IQOP_GRID_ALPHA)
    overlay_axes.legend(frameon=False)

    path_indices = np.arange(len(path_max))
    delta_axes.bar(
        path_indices,
        path_max,
        color=IQOP_DELTA_COLOR,
        alpha=IQOP_DELTA_ALPHA,
        label="maximum",
    )
    delta_axes.plot(
        path_indices,
        path_rms,
        color=IQOP_GUROBI_COLOR,
        marker="o",
        linewidth=IQOP_DELTA_LINE_WIDTH,
        label="RMS",
    )
    delta_axes.ticklabel_format(
        axis="y",
        style="sci",
        scilimits=IQOP_SCIENTIFIC_NOTATION_LIMITS,
    )
    delta_axes.set_title(f"Registered coordinate delta\nmax={metrics.global_max:.3e}, RMS={metrics.global_rms:.3e}")
    delta_axes.set_xlabel("toolpath index")
    delta_axes.set_ylabel("Euclidean separation")
    delta_axes.grid(axis="y", alpha=IQOP_GRID_ALPHA)
    delta_axes.legend(frameon=False)

    figure.suptitle(title)
    figure.tight_layout()
    return figure, list(axes_array), metrics


def plot_paths(
    paths: list[NEPath] | None,
    title: str = "NEPath Toolpaths",
    contour: NEPath | None = None,
    holes: list[NEPath] | None = None,
    sharp_corners: list[tuple[float, float]] | None = None,
    underfill_regions: list[NEPath] | None = None,
    figsize: tuple[float, float] = (10, 10),
) -> tuple[Figure, Axes]:
    """
    Plot toolpaths with optional contour, holes, sharp corners, and underfill regions.

    Parameters
    ----------
    paths : list[NEPath] | None
        List of Path objects to plot
    title : str
        Plot title
    contour : NEPath | None
        Contour boundary to plot
    holes : list[NEPath] | None
        Hole boundaries to plot
    sharp_corners : list[tuple[float, float]] | None
        List of (x, y) sharp corner points to highlight
    underfill_regions : list[NEPath] | None
        Underfill region paths to highlight
    figsize : tuple[float, float]
        Figure size (width, height)

    Returns
    -------
    tuple[Figure, Axes]
        Matplotlib figure and axis objects
    """
    fig, ax = plt.subplots(figsize=figsize)

    # Generate colors for paths using a colormap
    cmap = plt.cm.viridis
    n_paths = len(paths) if paths else 1

    # Plot contour if provided
    if contour is not None:
        x, y = contour.get_arrays()
        ax.plot(x, y, "k-", linewidth=2, label="Contour", zorder=10)

    # Plot holes if provided
    if holes:
        for i, hole in enumerate(holes):
            x, y = hole.get_arrays()
            ax.plot(x, y, "k--", linewidth=2, label="Hole" if i == 0 else None, zorder=10)

    # Plot underfill regions if provided
    if underfill_regions:
        for i, region in enumerate(underfill_regions):
            x, y = region.get_arrays()
            ax.fill(x, y, alpha=0.3, color="red", label="Underfill" if i == 0 else None, zorder=1)

    # Plot toolpaths
    if paths:
        for i, path in enumerate(paths):
            x, y = path.get_arrays()
            color = cmap(i / n_paths)
            ax.plot(x, y, "-", color=color, linewidth=1, alpha=0.8, zorder=5)
            # Mark start and end points
            if len(x) > 0:
                ax.plot(x[0], y[0], "go", markersize=4, zorder=15)  # Start: green
                ax.plot(x[-1], y[-1], "ro", markersize=4, zorder=15)  # End: red

    # Plot sharp corners if provided
    if sharp_corners:
        sc_x, sc_y = zip(*sharp_corners) if sharp_corners else ([], [])
        ax.scatter(sc_x, sc_y, c="orange", s=100, marker="*", label="Sharp corners", zorder=20, edgecolors="black")

    ax.set_aspect("equal")
    ax.set_title(title)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.grid(True, alpha=0.3)

    # Add legend if we have labeled items
    handles, labels = ax.get_legend_handles_labels()
    if handles:
        ax.legend(loc="upper right")

    # Add path count annotation
    if paths:
        ax.annotate(
            f"{len(paths)} paths", xy=(0.02, 0.98), xycoords="axes fraction", fontsize=10, verticalalignment="top", bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5)
        )

    plt.tight_layout()
    return fig, ax


def save_plot(fig: Figure, output_dir: str | Path, filename: str) -> Path:
    """
    Save a figure to the output directory.

    Parameters
    ----------
    fig : Figure
        The matplotlib figure to save
    output_dir : str | Path
        Directory to save the figure to
    filename : str
        Name of the output file (e.g., 'demo_CP.png')

    Returns
    -------
    Path
        Path to the saved file
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    filepath = output_path / filename
    fig.savefig(filepath, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return filepath


def plot_comparison(
    original_path: NEPath,
    resampled_path: NEPath,
    title: str = "Path Comparison",
    figsize: tuple[float, float] = (14, 5),
) -> tuple[Figure, list[Axes]]:
    """
    Plot original and resampled paths side by side for comparison.

    Parameters
    ----------
    original_path : NEPath
        The original path object
    resampled_path : NEPath
        The resampled path object
    title : str
        Overall title for the comparison
    figsize : tuple[float, float]
        Figure size (width, height)

    Returns
    -------
    tuple[Figure, list[Axes]]
        Matplotlib figure and list of axes objects
    """
    fig, axes = plt.subplots(1, 2, figsize=figsize)

    # Original path
    x_orig, y_orig = original_path.get_arrays()
    axes[0].plot(x_orig, y_orig, "b-o", markersize=8, label=f"Original ({original_path.length} pts)")
    axes[0].set_title("Original Path")
    axes[0].set_xlabel("X")
    axes[0].set_ylabel("Y")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    axes[0].set_aspect("equal")

    # Resampled path
    x_res, y_res = resampled_path.get_arrays()
    axes[1].plot(x_res, y_res, "r-o", markersize=4, label=f"Resampled ({resampled_path.length} pts)")
    axes[1].set_title("Resampled Path")
    axes[1].set_xlabel("X")
    axes[1].set_ylabel("Y")
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)
    axes[1].set_aspect("equal")

    fig.suptitle(title)
    plt.tight_layout()
    return fig, list(axes)
